services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: personal_health_backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      # Ahora persiste el DB que tu código abre en /app/backend/data
      - ./backend/data:/app/data
    entrypoint: >
      sh -c "
        python rdf_util.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8000
    container_name: app-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "80:80"
    depends_on:
      - backend
